apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: dev-env
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/hugywugy43/dev-env-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
            - containerPort: 5050
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: dev-env
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: pgadmin
      port: 5050
      targetPort: 5050
    - name: api-docs
      port: 8000
      targetPort: 8000

