apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dev-env-ingress
  namespace: dev-env
  annotations:
    # Подсказываем ALB Ingress Controller, что этот Ingress нужно обрабатывать ему
    kubernetes.io/ingress.class: yc-alb-ingress-controller
spec:
  # Для новых контроллеров (если IngressClass создан) тоже можно указать класс
  ingressClassName: yc-alb-ingress-controller
  rules:
    - host: dev-env.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 8080
          - path: /pgadmin
            pathType: Prefix
            backend:
              service:
                name: pgadmin
                port:
                  number: 80

